# Generated by Django 4.0.6 on 2022-07-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('second_price', models.IntegerField()),
                ('area_size', models.CharField(blank=True, max_length=200, null=True)),
                ('bedrooms', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('garages', models.IntegerField(default=0)),
                ('year_built', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('video_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('virtual_tour_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('managed_by_manyumba', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.agents')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.cities')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_status', models.CharField(max_length=600)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name': 'PropertyType',
                'verbose_name_plural': 'PropertyTypes',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('home_tag', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties')),
            ],
            options={
                'verbose_name': 'Properties',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.propertystatus'),
        ),
        migrations.AddField(
            model_name='properties',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.type'),
        ),
        migrations.CreateModel(
            name='FloorPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=1)),
                ('plan_size', models.IntegerField(default=1)),
                ('plan_image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties')),
            ],
        ),
    ]
