# Generated by Django 4.0.6 on 2022-07-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaldetails',
            options={'verbose_name': 'AdditionalDetails', 'verbose_name_plural': 'AdditionalDetails'},
        ),
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name': 'Agents', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Cities', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Features', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='floorplans',
            options={'verbose_name': 'FloorPlans', 'verbose_name_plural': 'FloorPlans'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Properties', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'PropertyImages', 'verbose_name_plural': 'PropertyImages'},
        ),
        migrations.AlterModelOptions(
            name='propertystatus',
            options={'verbose_name': 'PropertyStatus', 'verbose_name_plural': 'PropertyStatus'},
        ),
    ]
