# Generated by Django 4.0.6 on 2022-07-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0003_additionaldetails_property_properties_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
