# Generated by Django 4.0.6 on 2022-07-29 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseListing', '0005_remove_properties_second_price_properties_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
