# Generated by Django 4.0.6 on 2022-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0008_properties_approved_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplans',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
