# Generated by Django 4.0.6 on 2022-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0010_alter_agents_picture_alter_floorplans_plan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Gateman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Play_Area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Swimming_Pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='WFI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='Water',
            field=models.BooleanField(default=False),
        ),
    ]
