# Generated by Django 4.0.6 on 2022-09-01 20:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0011_properties_ac_properties_balcony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='units',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('house_type', models.CharField(max_length=200)),
                ('rent', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('arrears', models.IntegerField(default=0)),
                ('vacant', models.BooleanField(default=True)),
                ('house_featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties')),
            ],
        ),
    ]
