# Generated by Django 4.0.6 on 2022-09-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0012_properties_available_rooms_properties_units_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='default_house_type',
            field=models.CharField(default='single', max_length=100),
            preserve_default=False,
        ),
    ]
