# Generated by Django 4.0.6 on 2022-09-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0013_properties_default_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start_date', models.DateField(auto_now_add=True)),
                ('lease_end_date', models.DateField()),
                ('lease_documents', models.FileField(blank=True, null=True, upload_to='')),
                ('current_status', models.BooleanField(default=False)),
                ('running_balance', models.FloatField(blank=True, default=0, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.tenant')),
            ],
        ),
    ]
