# Generated by Django 4.0.6 on 2022-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0015_tenant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='sur_name',
        ),
    ]
