# Generated by Django 4.0.6 on 2022-09-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0016_remove_tenant_sur_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
