# Generated by Django 4.0.6 on 2022-09-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0017_alter_tenant_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_incurred', models.FloatField(default=0)),
                ('fully_paid', models.BooleanField(default=False)),
                ('date_generated', models.DateField()),
                ('amount_paid', models.FloatField(blank=True, default=0, null=True)),
                ('amount_due', models.FloatField(blank=True, default=0, null=True)),
                ('previous_over_dues', models.FloatField(blank=True, default=0, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.properties')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.house')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseListing.tenant')),
            ],
        ),
    ]
