# Generated by Django 4.0.6 on 2022-09-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0019_properties_security_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='agent',
        ),
    ]
