# Generated by Django 4.0.6 on 2022-09-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0020_remove_properties_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'LandSizes',
                'verbose_name_plural': 'LandSizes',
            },
        ),
    ]
