# Generated by Django 4.0.6 on 2022-09-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0021_landsizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='landsize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseListing.landsizes'),
        ),
    ]
