# Generated by Django 4.0.6 on 2022-09-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0022_properties_landsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='DomesticSewage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='ElectricSupply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='RainWaterDrainage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='WaterSupply',
            field=models.BooleanField(default=False),
        ),
    ]
