# Generated by Django 4.0.6 on 2022-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0023_properties_domesticsewage_properties_electricsupply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
