# Generated by Django 4.0.6 on 2022-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0026_properties_slug_alter_properties_approved_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorgageLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank='True', max_length=100, null=True)),
                ('phone', models.CharField(blank='True', max_length=100, null=True)),
                ('email', models.CharField(blank='True', max_length=100, null=True)),
                ('employment_type', models.CharField(blank='True', max_length=100, null=True)),
                ('gross_income', models.CharField(blank='True', max_length=100, null=True)),
                ('convinient_time', models.CharField(blank='True', max_length=100, null=True)),
                ('property_price', models.CharField(blank='True', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'MorgageLeads',
                'verbose_name_plural': 'MorgageLeadss',
            },
        ),
    ]
