# Generated by Django 4.0.6 on 2022-10-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseListing', '0027_morgageleads_alter_properties_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morgageleads',
            name='property_price',
            field=models.IntegerField(blank='True', null=True),
        ),
    ]
